AWSTemplateFormatVersion: "2010-09-09"
Description: go-back infrastructure definition
Resources:
  JobComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeEnvironmentName: go-back-compute-environment
      ComputeResources:
        MinvCpus: 0
        DesiredvCpus: 4
        MaxvCpus: 4
        Ec2KeyPair: go-back
        InstanceRole: arn:aws:iam::528784232475:instance-profile/ecsInstanceRole
        ImageId: ami-0f81f2fedbcf0d840
        InstanceTypes:
          - optimal
        SecurityGroupIds: !Ref SecurityGroups
        Subnets: !Ref Subnets
        Type: EC2
      ServiceRole: arn:aws:iam::528784232475:role/service-role/AWSBatchServiceRole
      Type: MANAGED
  JobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - ComputeEnvironment: !Ref JobComputeEnvironment
          Order: 1
      JobQueueName: go-back
      Priority: 1
  JobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      ContainerProperties:
        Command:
          - "-bucket"
          - !Ref BucketName
          - "-region"
          - !Ref BucketRegion
          - "-backupfolder"
          - "/work"
          - "-namespace"
          - !Ref MetricsNamespace
        Environment:
          - Name: GL_TOKEN
            Value: !Ref GitLabToken
          - Name: GH_TOKEN
            Value: !Ref GitHubToken
        Image: 528784232475.dkr.ecr.us-west-2.amazonaws.com/go-back:latest
        JobRoleArn: arn:aws:iam::528784232475:role/go-back-ecs-execution-role
        Memory: 2000
        MountPoints:
          - ContainerPath: /work
            SourceVolume: workdir
        Vcpus: 4
        Volumes:
          - Host:
              SourcePath: /work
            Name: workdir
      JobDefinitionName: go-back
      RetryStrategy:
        Attempts: 2
      Timeout:
        AttemptDurationSeconds: 3600
      Type: container
  TriggerBackupJob:
    Type: AWS::Events::Rule
    Properties:
      Description: Triggers a full back of GitLab and GitHub
      ScheduleExpression: rate(1 day)
      Targets:
        - Arn: !Ref JobQueue
          RoleArn: !GetAtt SubmitGoBackJobRole.Arn
          BatchParameters:
            JobDefinition: !Ref JobDefinition
            JobName: go-back-full-repos-backup-to-s3
          Id: go-back
  SubmitGoBackJobRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: go-back-allow-job-submit
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: batch:SubmitJob
                Resource:
                  - !Ref JobQueue
                  - !Ref JobDefinition
Parameters:
  GitHubToken:
    Type: String
    Description: GitHub token
  GitLabToken:
    Type: String
    Description: GitLab token
  BucketName:
    Type: String
    Description: S3 bucket name
  BucketRegion:
    Type: String
    Description: S3 bucket region
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
  SecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
  MetricsNamespace:
    Type: String
